# Python Tutorial for Astronomy

Roy T. Smart

2023-05-30

## Jupyter basics

Jupyter notebooks are a way of writing a Python program in an interactive way. Information is organized into "cells", of which there are two usual types: code cells and Markdown cells.

To evaluate a cell use `SHIFT`+`ENTER`

### Markdown cells

Markdown is a markup language that allows for formatting text and math inside the Jupyter notebook.

If your current cell is in edit mode (green border), press `ESC` to change to command mode (blue border), then `m` to change the current cell to Markdown mode, and the `Enter` to change back into edit mode.

### Code cells

Code cells automatically print the value on the last line of the cell

In [1]:
"Hello World"

'Hello World'

If we assign the value to a variable using `=`, nothing is printed.

In [2]:
a = "Hello World"

We can still easily see the value of the variable 

In [3]:
a

'Hello World'

If we want to supress output, use a semicolon at the end of the expression

In [4]:
a;

To print anything not on the last line of a cell, we can use the `print()` function.

In [5]:
print("here")
print(a)

here
Hello World


## Outline

 - Built-in Python types
     - Booleans
     - Numbers
     - Strings
     - Lists
     - Tuples
     - Dictionaries
 - Control flow
     - Conditional expressions (if/else)
     - Loops
     - List comprehension
     - Functions
 - Numpy Arrays
     - Defining new arrays
     - Important attributes
     - Arithmetic
     - Broadcasting
     - Indexing
     - Plotting using matplotlib
 - Astropy
     - Quantity
     - Time
     - Skycoord
     - WCS
 - Sunpy
     - GOES XRS example
     - AIA example

## Built-in Python types

All variables in Python have a type (boolean, numeric, strings, user-defined, etc.)

We can use the `type()` function to check the type of any variable. This is really helpful when you're trying to debug issues

In [6]:
type(a)

str

### Booleans

`True` and `False` (capitalized) are the two possible values of the `bool` type

In [7]:
bool_0 = False
bool_1 = True

If we use the `type()` function on these variables, we can see that they are indeed `bool`s

In [8]:
type(bool_0)

bool

The `not` operator inverts the boolean value

In [9]:
not bool_0

True

The `and` operator performs the logical AND operation between two boolean values

In [10]:
bool_0 and bool_1

False

The `or` operator performs the logical OR operation between two boolean values

In [11]:
bool_0 or bool_1

True

### Numbers

Define an integer

In [12]:
num_1 = 2
type(num_1)

int

Define a floating-point number

In [13]:
num_2 = 3.1
type(num_2)

float

Addition and subtraction

In [14]:
num_1 + num_2

5.1

In [15]:
num_1 - num_2

-1.1

Multiplication and division

In [16]:
num_1 * num_2

6.2

In [17]:
num_1 / num_2

0.6451612903225806

Integer division

In [18]:
num_1 // num_2

0.0

Modulo division

In [19]:
num_1 % num_2

2.0

Equality

In [20]:
num_1 == num_2

False

Greater/less than

In [21]:
num_1 > num_2

False

In [22]:
num_1 < num_2

True

### Strings

Can be made with either single quotes or double quotes

In [23]:
str_1 = 'foo'

In [24]:
str_2 = "bar"

Concatenate two strings using the `+` operator

In [25]:
str_1 + str_2

'foobar'

f-strings (format strings) are usually the best way to build up strings. They are prepended with an 'f' and use curly braces to reference variables.

In [26]:
f"Some of the variables we've defined are: bool_1={bool_1}, num_1={num_1}, str_1={str_1}"

"Some of the variables we've defined are: bool_1=True, num_1=2, str_1=foo"

### Lists

Define a list using square brackets. The elements of a list are allowed to be any type, and they all can be different types.

In [27]:
list_1 = [1, False, "foo"]
list_2 = [2, True, "bar"]

Define as list using the `list()` constructor and the `range()` function.

In [28]:
list_3 = list(range(6))
list_3

[0, 1, 2, 3, 4, 5]

Compute the length of the list using the `len()` function

In [29]:
len(list_1)

3

Concatenate two lists using the `+` operator

In [30]:
list_1 + list_2

[1, False, 'foo', 2, True, 'bar']

Add item to the end of a list using the `append()` method

In [31]:
list_1.append(3)
list_1

[1, False, 'foo', 3]

Get the value at a given index

In [32]:
list_1[2]

'foo'

Set the value at a given index

In [33]:
list_1[2] = "qux"
list_1

[1, False, 'qux', 3]

Slice list using `:` operator

In [34]:
start = 1
stop = 5
step = 2
list_3[start:stop:step]

[1, 3]

start, stop, and step are all optional when slicing

In [35]:
list_3[start:]

[1, 2, 3, 4, 5]

In [36]:
list_3[:stop]

[0, 1, 2, 3, 4]

In [37]:
list_3[::step]

[0, 2, 4]

`start`, `stop`, and `step` can all be negative. If `start` or `stop` is negative, it is equivalent to indexing from the back of the list. For example, `-1` is the last element, `-2` is the second-to-last element, etc.

In [38]:
list_3[:-2]

[0, 1, 2, 3]

If `step` is negative it means that we are stepping through the list backwards. For example, indexing the list with `::-1` reverses the list

In [39]:
list_3[::-1]

[5, 4, 3, 2, 1, 0]

### Tuples

Tuples are very similar to lists, but they are read-only and can't be modified after creation.

Define a tuple with paretheses

In [40]:
tuple_1 = (3, "baz")

Define a tuple without paretheses

In [41]:
tuple_2 = 4, "bam"

Since tuples are read-only, we cannot set elements to a new value

In [42]:
tuple_1[1] = "buzz"

TypeError: 'tuple' object does not support item assignment

### Dictionaries
Dictionaries are mappings between keys and values

Define a dict using curly braces and use colons to delimit key from value. The keys and values can be any type.

In [43]:
dict_1 = {1: "foo", "bar": False}

If the keys are strings, it can often be cleaner to use the `dict()` constructor

In [44]:
dict_2 = dict(a=1, b=2, c=3)

Use square brackets get/set the value at a given key

In [45]:
dict_1[1]

'foo'

In [114]:
dict_1["ham"] = "spam"
dict_1

{1: 'foo', 'bar': False, 2: 'spam', 'ham': 'spam'}

## Control flow

### Conditional expressions

Basic structure of `if`/`else` in Python.

In [47]:
if bool_0:
    print("if")
elif bool_1:
    print("elif")
else:
    print("else")

elif


Note that `elif` and `else` are optional. You're allowed to use only the `if` if that's all you need

In [48]:
if bool_0:
    print("here!")

If you want, sometimes it can be cleaner to use the single-line version of `if`/`else`

In [49]:
"foo" if bool_0 else "bar"

'bar'

### Loops

Basic structure of a `for` loop in python

In [50]:
for item in list_1:
    print(item)

1
False
qux
3


Use the `range()` function to create an integer sequence up to a given stopping value (exclusive)

In [51]:
for i in range(3):
    print(i)

0
1
2


By default the `start=` argument of `range()` is zero. You can specify the start value by providing two arguments

In [52]:
for i in range(1, 3):
    print(i)

1
2


You can use the `enumerate()` function instead of using `range(len(list_1))`

In [53]:
for i, item in enumerate(list_1):
    print(i, item)

0 1
1 False
2 qux
3 3


Use the `zip()` function to loop over two lists simultaneously

In [54]:
for item_1, item_2 in zip(list_1, list_2):
    print(item_1, item_2)

1 2
False True
qux bar


### List comprehension

Often we want to loop over a list and modify its elements, list comprehension allows us to do this in a much cleaner way

In [55]:
[2 * i for i in list_1]

[2, 0, 'quxqux', 6]

Compare this to

In [113]:
list_new = []
for i in list_1:
    list_new.append(2 * i)
list_new

[2, 0, 'quxqux', 6]

We can also combine list comprehension and the single-line versions of if/else to replace more complicated loops

In [56]:
[2 * i if i == 1 else i for i in list_1]

[2, False, 'qux', 3]

### Functions

The `def` keyword is used to define a function

In [57]:
def multiply_by_two(n):
    return 2 * n

Use parentheses to call the function

In [58]:
multiply_by_two(3)

6

Specifying the name of the argument is optional

In [59]:
multiply_by_two(n=3)

6

You can define optional arguments to a function by providing a default value

In [60]:
def multiply(m, n=2):
    return m * n

Call the function using the default value for `n`

In [61]:
multiply(3)

6

Call the function with a non-default value for `n`

In [62]:
multiply(3, 3)

9

## Numpy Arrays

**NEVER EVER EVER USE FOR LOOPS TO DO MATH!!!**

Numpy arrays are the standard way to do numerical computations in Python.

Import the Numpy library into the current namespace using the `import` keyword and give it the alias `np`

In [63]:
import numpy as np

### Defining numpy arrays

Define a 1D array using a list

In [64]:
arr_1d = np.array(list_3)
arr_1d

array([0, 1, 2, 3, 4, 5])

Define a 2D array using a list of lists

In [65]:
arr_2d = np.array([
    [0, 1, 2],
    [3, 4, 5],
])
arr_2d

array([[0, 1, 2],
       [3, 4, 5]])

Define a 3D array using a list of arrays

In [66]:
arr_3d = np.array([arr_2d, arr_2d])
arr_3d

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

Define a 2D array of zeros using `numpy.zeros()`

In [67]:
nrows = 2
ncols = 3
shape = (nrows, ncols)
arr_zeros = np.zeros(shape)
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

Define an uninitialized array using `numpy.empty()`

In [68]:
np.empty(shape)

array([[0., 0., 0.],
       [0., 0., 0.]])

Define a 1D linear sequence using `numpy.linspace()`.

In [69]:
x = np.linspace(start=0, stop=1, num=6)
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

Define a 2D normal random array using `numpy.random.normal()`.

In [70]:
mean = 0
std = 2
np.random.normal(loc=mean, scale=std, size=shape)

array([[ 0.59076725,  0.39046379,  1.62363834],
       [-1.8691808 ,  0.03641342, -0.6281594 ]])

### Array attributes

The `shape` attribute is a tuple of integers representing the number of elements in each axis of the array

In [71]:
arr_1d.shape

(6,)

In [72]:
arr_2d.shape

(2, 3)

The `size` attribute is an integer representing the total number of elements in the array

In [73]:
arr_1d.size

6

In [74]:
arr_2d.size

6

The `ndim` attribute is an integer representing the number of dimensions (or axes) in the array

In [75]:
arr_1d.ndim

1

In [76]:
arr_2d.ndim

2

### Array arithmetic

All of the same arithmetic operators defined for Python scalars (`int` and `float`) are defined for numpy arrays. The difference is that they are vectorized operations, which implicitly loop over the whole array, applying the arithmetic operation elementwise.

Add two 1D arrays

In [77]:
arr_1d + arr_1d

array([ 0,  2,  4,  6,  8, 10])

Multiply two 2D arrays

In [78]:
arr_2d * arr_2d

array([[ 0,  1,  4],
       [ 9, 16, 25]])

### Broadcasting

For the vectorized operation to be valid, the operands must be *broadcastable*. Note how adding `arr_1d` to `arr_2d` results in an error

In [79]:
arr_1d + arr_2d

ValueError: operands could not be broadcast together with shapes (6,) (2,3) 

Arrays with the exact same shape are automatically broadcastable, but there are other conditions where arrays are broadcastable.  If the size of any dimensions is `1`, the array is stretched along that dimension to match the shape of the other array. For example, one array that is broadcastable with `arr_2d` is an array with the same number of columns, but only one row.

In [80]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
arr_2d.shape

(2, 3)

In [82]:
arr_row = np.array([[0, -1, -2]])
arr_row.shape

(1, 3)

In [83]:
arr_2d + arr_row

array([[0, 0, 0],
       [3, 3, 3]])

We can use the `numpy.broadcast_to()` function to explicitly broadcast the array to a given shape.

In [84]:
np.broadcast_to(arr_row, shape=arr_2d.shape)

array([[ 0, -1, -2],
       [ 0, -1, -2]])

Another example of an array that is broadcastable with `arr_2d` is an array with the same number of rows, but only one column.

In [85]:
arr_col = np.array([
    [0],
    [-1],
])
arr_col.shape

(2, 1)

In [86]:
arr_2d + arr_col

array([[0, 1, 2],
       [2, 3, 4]])

In [87]:
np.broadcast_to(arr_col, shape=arr_2d.shape)

array([[ 0,  0,  0],
       [-1, -1, -1]])

Note that `arr_row` and `arr_col` are also broadcastable with each other

In [88]:
arr_row.shape, arr_col.shape

((1, 3), (2, 1))

In [89]:
arr_row + arr_col

array([[ 0, -1, -2],
       [-1, -2, -3]])

Array don't need to have the same number of dimensions to be broadcastable. Dimensions are compared from right to left, so for a 1D array and a 2D array to be broadcastable, the last dimension of the 2D array must be compatible with the only dimension of the 1D array.

In [90]:
arr_2d.shape

(2, 3)

In [91]:
arr_row_1d = np.array([0, -1, -2])
arr_row_1d.shape

(3,)

In [92]:
arr_2d + arr_row_1d

array([[0, 0, 0],
       [3, 3, 3]])

For this reason, scalar values (`int` and `float`) are always broadcastable with any array, since they have an empty shape

In [115]:
np.array(num_1).shape

()

In [93]:
arr_2d + 2

array([[2, 3, 4],
       [5, 6, 7]])

We can use the `numpy.broadcast_shapes()` function to compute the broadcasted shape given the input shapes without having to define real arrays

In [94]:
shape_1 = (6, 1)
shape_2 = (5, 1, 4)
np.broadcast_shapes(shape_1, shape_2)

(5, 6, 4)

### Indexing numpy arrays

#### Basic array indexing

Indexing a 1D array using an integer returns a scalar

In [95]:
arr_1d

array([0, 1, 2, 3, 4, 5])

In [96]:
arr_1d[1]

1

Indexing a 2D array using an integer returns a row of the array

In [97]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [98]:
arr_2d[1]

array([3, 4, 5])

We can slice arrays just like lists

In [99]:
start, stop, step

(1, 5, 2)

In [100]:
arr_1d[start:stop:step]

array([1, 3])

Just like with lists, `start`, `stop`, and `step` are optional. If we use just an empty slice on any array, we get the same array back.

In [101]:
arr_1d[:]

array([0, 1, 2, 3, 4, 5])

Unlike lists, we can use a `tuple` of indices on a numpy array if we want to index multiple dimensions simultanously. For example using a tuple of two integers on a 2D array returns a scalar

In [102]:
arr_2d[1, 2]

5

We already saw that we can select a row of a 2D array by indexing with a single integer

In [103]:
arr_2d[1]

array([3, 4, 5])

Indexing the 2D array with a tuple of an integer and a slice returns the same result

In [104]:
arr_2d[1, :]

array([3, 4, 5])

But if we want to select a column, instead of a row, we can put the slice first

In [105]:
arr_2d[:, 1]

array([1, 4])

We can use the ellipses (`...`) to replace an arbitrary number of colons (`:`), and we get one ellipses per indexing operation. For example, we can replace the colon in the last cell with an ellipses and get the same result

In [106]:
arr_2d[..., 1]

array([1, 4])

But it's more useful for higher-dimensional arrays, consider how we use the ellipses to replace two colons when indexing a 3D array

In [107]:
arr_3d[:, :, 1]

array([[1, 4],
       [1, 4]])

In [108]:
arr_3d[..., 1]

array([[1, 4],
       [1, 4]])

### Boolean array indexing

Numpy arrays do not always have a numeric type, we can have an array of booleans.

Create a boolean array from a list of booleans.

In [109]:
arr_bool = np.array([True, False, True])

Usually boolean arrays occur as a result of applying the comparison operators (`==`, `>`, `<`, etc.) to arrays

In [110]:
arr_bool_2d = arr_2d > 1
arr_bool_2d

array([[False, False,  True],
       [ True,  True,  True]])

This `arr_bool_2d` can now be used to index `arr_2d` and select only the elements that are greater than one

In [111]:
arr_2d[arr_bool_2d]

array([2, 3, 4, 5])

We can also combine basic array indexing and boolean array indexing. In this example we select the first and last column of `arr_2d`

In [112]:
arr_2d[:, arr_bool]

array([[0, 2],
       [3, 5]])

### Integer array indexing